mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index),
    path('sosmed/', include('sosmed.urls')),
    path('admin/', admin.site.urls),
]

sosmed/urls.py
from django.urls import path, re_path

from . import views

app_name = 'sosmed'

urlpatterns = [
    re_path(r'delete/(?P<delete_id>[0-9]+)$', views.delete, name='delete'),
    re_path(r'update/(?P<update_id>[0-9]+)$', views.update, name='update'),
    re_path(r'^create/', views.create, name='create'),
    re_path(r'^$', views.list, name='list')
]

sosmed/models.py
from django.db import models

# Create your models here.
class Instagram(models.Model):
    nama_depan      = models.CharField(max_length=100)
    nama_belakang   = models.CharField(max_length=100)
    username        = models.CharField(max_length=100)

    def __str__(self) -> str:
        return "{}. {}".format(self.id, self.username)

sosmed/forms.py
from django import forms

from .models import Instagram

class InstagramForm(forms.ModelForm):
    class Meta:
        model = Instagram
        fields = [
            'nama_depan',
            'nama_belakang',
            'username',
        ]

mywebsite/views.py
# from django.http import HttpResponse
from django.shortcuts import render


# method view
def index(request):
    context = {
        'page_title':'Home',
    }
    return render(request, 'index.html', context)

sosmed/views.py
from django.shortcuts import render, redirect

# Create your views here.

from .models import Instagram

from .forms import InstagramForm

def update(request, update_id):
    akun_update = Instagram.objects.get(id=update_id)

    data = {
        'nama_depan'    : akun_update.nama_depan,
        'nama_belakang' : akun_update.nama_belakang,
        'username'      : akun_update.username,
    }
    akun_form = InstagramForm(request.POST or None, initial=data, instance=akun_update)

    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()

        return redirect('sosmed:list')
    
    context = {
        "page_title":"Update Akun",
        "akun_form": akun_form,
    }

    return render(request,'sosmed/create.html',context)

def delete(request, delete_id):
    Instagram.objects.filter(id=delete_id).delete()
    return redirect('sosmed:list')

def create(request):
    akun_form = InstagramForm(request.POST or None)

    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()

        return redirect('sosmed:list')
    
    context = {
        "page_title":"Create Akun",
        "akun_form": akun_form,
    }

    return render(request,'sosmed/create.html',context)

def list(request):
    acount = Instagram.objects.all()

    context = {
        'page_title':'Sosial Media',
        'acount':acount,
    }

    return render(request, 'sosmed/list.html', context)

sosmed/templates/sosmed/create.html
{% extends "base.html" %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{akun_form.as_table}}
        </table>
        <button type="Submit">Kirim</button>
    </form>
{% endblock contents %}

sosmed/templates/sosmed/list.html
{% extends "base.html" %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <table class="table ">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Username</th>
                <th scope="col">Delete Data</th>
                <th scope="col">Update Data</th>
            </tr>
        </thead>
        <tbody>
            {% for akun in acount %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{akun.nama_depan}}</td>
                    <td>{{akun.nama_belakang}}</td>
                    <td>{{akun.username}}</td>
                    <td><a class="btn btn-danger" href="{% url 'sosmed:delete' akun.id %}">Delete</td>
                    <td><a class="btn btn-warning" href="{% url 'sosmed:update' akun.id %}">Update</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'sosmed:create' %}">Tambah</a>
{% endblock contents %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}

        {% endblock title %}
    </title>
    {% include "snippets/style.html" %}
</head>
<body>

    <div class="container bg-light shadow mt-5 ">
        {% block contents %}
    
        {% endblock contents %}
    </div>

    {% include "snippets/script.html" %}
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}
    {{page_title}}
{% endblock title %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <p>{% lorem 2 b random %}</p>
    <h4><a href="sosmed/">Sosmed</a></h4>
{% endblock contents %}

templates/snippets/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark " id="myNav">
    <a class="navbar-brand" href="#">
        <img style="height: 30px;" src="{% static "img/logo.png" %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>      
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blogs:index' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
        </ul>        
    </div>
</nav>

templates/snippets/script.html
{% load static %}

<script src="{% static "vendor/jquery/jquery.js" %}"></script>
    
<script src="{% static "vendor/popper/popper.js" %}"></script>
    
<script src="{% static "vendor/bootstrap/bootstrap.js" %}"></script>

<!-- <script src="{% static "js/scrolling.js" %}"></script> -->

templates/snippets/style.html
{% load static %}
<link rel="stylesheet" href="{% static "vendor/bootstrap/bootstrap.css" %}">